### ISSUE TITLE
General Checklist

### ISSUE THREAD

**Issue by llelectronics** [blue-systems/netrunner-next#58]
== BASIC TESTS ==

* basic tests:
* [ ] all programs there? see below for program list
* [x] installation works
* [x] german install works
* [ ] uefi install works
* [x] logout/login works after second boot
* [x] tty1 - tty7 ALT+STRG+F1 - F7
* [x] Version name and number is correct? in calamares, in My Computer,after install in grub?
* [x] sddm artwork is correct
* [x] Sound works
* [x] Network works
* [x] sftp + smb connections work
* [x] Samba-Mounter works (even after reboot)
* [x] apt-get update does not throw errors
* [x] Synaptic installing qmmp app works
* [x] synaptic: refresh works after uncommenting "testing"
* [x] synaptic: repo list correct?
 calamares ds9-artwork ds9-common extras netrunner-desktop netrunner
![Screenshot_20200223_122029](https://user-images.githubusercontent.com/840070/75111185-32946f00-5637-11ea-8784-eb5ecc369144.png)

----

* plasma checks:
* [x] meta key works to invoke menu
* [x] menu sorted alphabetic, that is the categories and the menu entrie
* [x] drag windows from titlebar
* [x] Panel configured correctly
* [x] Artwork configured correctly
* [x] Right Click menu configured correctly

----

* software checks:
* [x] firefox loads
* [x] thunderbird loads
* [x] steam loads
* [x] net-tools installed
* [x] inxi installed
* [x] every app starts
* [x] Mintupdate starts and software-properties is accessible

----

* firefox checks:
* [x] ublock works?
* [ ] ublock filter rules correct with blocking google hidden stuff?
* [x] downloading google logo works?
* [x] rt.com flash works? (Flash works, about flash page after allowing flash) *rt.com is not using flash anymore*
* [x] magnet torrent works? https://www.limetorrents.cc/Introducing-UNIX-and-Linux-(Grassroots)-by-Mike-Joy--True-PDF--torrent-8660949.html

-------------------------

== SOFTWARE CHECKLIST in Menu ==

games 10:
* burgerspace
* chess (gnome-chess) [is chessengine working after making first move?]
* frozen bubble
* gltron
* gnome-sudoku/gnudoq
* kbreakout
* kmahjongg
* kmines
* ksnakeduel
* steam [works?]

----

graphics 5:
* gimp
* gwenview
* inkscape
* krita
* skanlite (/simplescan)

----

internet 6:
* firefox
* kde marble [search for street works, e.g. Abbot Kinney?] 
* pidgin
* qttransmission [clicking on a magnet link in ff works?]
* skype
* thunderbird
--
* (x11vncserver) should only be in core? -> move to: Settings
(steam hidden)

----

multimedia 8:
* audacious
* gmusicbrowser
* handbrake
* kamoso (/cheese)
* kdenlive
* pulseaudio volume control
* smplayer (vlc)
* yarock
--
* vokoscreen (should move to Utilities), simplescreenrecorder
* (mpv hidden)

----

office 4:
* LO suite
* calc
* impress
* writer
--
* okular (should go to utilities)
* (LO math hidden)
* (LO draw hidden)
* (LO Base hidden)
* (Kmail hidden)

----

settings 5:
* grub customizer
* kvantum manager
* print settings
* system settings
* X11VNC Server

----

system 11 + 1:
* temp. removed, needs to be back: windows wireless (ndisgtk)
--
* (calamares) , removed after install
* discover
* dolphin
* info center
* kde partition manager
* konsole
* ksysguard
* kwallet manager
* network drives
* synaptic package manager (or octopi in rolling)
* update manager
* yakuake
--
* hidden: virtualbox (/qemu) should move to Utilities

----

utilities 8:
* ark
* isowriter (/suse imagwriter or isoimagewriter/-neon)
* kate
* kcalc
* okular
* spectacle
* virtualbox (/qemu)
* vokoscreen (simplescreenrecorder?)

--
* hidden: kvantum manager

----

web 4:
* Hooktube
* Opendesktop.org
* Skype-Web
* Telegram
* Whatsapp
