### ISSUE TITLE
Netrunner 22 Todo

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#83]
https://pub.netrunner.com/.testing/
CHECK #87 after solving these issues:
- [x] WIFI completely missing (notice: that is MOBILE ADAPTER, NOT wifi....):
![Screenshot_20220708_163903](https://user-images.githubusercontent.com/840070/178035455-54d8d8b9-ab60-49fc-98ec-6e4d5db7432d.png)
- [x] add network: i can find smb network shares, but it STILL doesnt accept any IP
![Screenshot_20220701_122617](https://user-images.githubusercontent.com/840070/176898082-5791893b-b0fc-4119-ae17-29335612a5fa.png)
- [x] add network drive: the icon under Network folder is not executable default, should be added permission without re-asking again
- [x] there is an empty category Lost and Found in menu
- [x] Volume 7 win is missing before systray, and in systray, the regular volume icon should be hidden (as it was previous netrunner 21)
- [x] marble: get directions is still not working for years now, please check upstream
-
- [x] wrong plymouth start theme
- [x] yakuake comes up open when logging in
- [x] dolphin completely missing all configs
- [x] also many other settings like window plcaements, etc all gone
- [x] panel at bottom missing yakuake, possibly other things (not sure as all over configs are wrong)
- stopped testing there
---------
- [x] System Settings: should be normal sidebar view, not old grid
- [x] System Settings: Color scheme: error about missing color scheme, needs to be checked to get rid of that message
- [x] check why for "apt install" no longer the TAB fucntion works to suggest autocomplete any package name 
- [x] install iputils-ping
- [x] stop xapian api process from going off and clogging the whole machine (we fixed this long time ago, not it seems it is back)
- [x] FF: Remove "Import Bookmarks" item from Bookmark category
- @ScarlettGatelyMoore SMB STILL not solved(?):
- It is the .LOCAL added at end which is screwing the network big time, so just removing that makes me access everything fine like before or elswhere...:
- [x] STILL cannot access any SMB network drives,  they work fine from the same machine with e.g. Manjaro KDE
- [x] that local likely prevents me also from accessing zynthbox via browser by simply typing: zynthbox.local , so it needs fixing priority, as I cant do any work from this machine right now
![Screenshot_20220418_100724](https://user-images.githubusercontent.com/840070/163779601-9a570ab4-9fd9-473d-98e7-03f227b95bf6.png)
- [x] There is an EMPTY category shown (Science&Math) even though no icons are there... this should not be, so it is some issue or reason

--------
done:
@adriaandegroot 
- [x] Installation which with iso before, now made my machine UNBOOTABLE:
![Screenshot_20220418_100419](https://user-images.githubusercontent.com/840070/163779575-3ab7b6a5-1fce-4d04-b260-d150bff08527.png)
- [x] "My computer" desktop icon doesnt work
- [x] Hooktube is still there?
- [x] CALAMARES FAILS to install
- [x] grub: after installation, menu should read "Netrunner 22" if to pick from various installed os
- [x] Dolphin: Has NO PREVIEWS options
- [x] Dolphin: doesnt know the SMB protocol, shows no networks
- [x] Dolphin: Network: Add Network folder: KCM not found, error
- [x] boot up from usb: lets remove any auto-disk check routine completely from that iso
- [x] Calamares, GRUB, ABOUT CONFIG: replace all VERSIONS with "Netrunner 22", NOT 21 or XOXO
- [x] Calamares icon is MISSING on desktop in LIVE MODE (dont show it AFTER installed!)
- [x] Firefox: Link to Netrunner forum is WRONG, should be: https://support.blue-systems.com/
- [x] Menu: remove/hide "TERMIT"
- [x] Menu: Web: remove "hooktube" webapps
- [x] systray: hide Yakuake
- [x] Disable Volume Mixer Win7
- [x] use this wallpaper default to replace XOXO: https://my.opendesktop.org/s/jsFNQpc5QLBzcCw

**Comment by Justinzobel** [comment]
@star-buck just for clarification do you want TERMIT and hooktube applications removed from the install or just their menu entries?

**Comment by Justinzobel** [comment]
Have fixed Netrunner Forum URL and icon in https://www.opencode.net/netrunner/netrunner-settings-firefox - it just needs the deb built and uploaded.

**Comment by Justinzobel** [comment]
Calamares branding and unsquashfs fixed in https://www.opencode.net/netrunner/calamares-desktop by @UriHerrera

**Comment by Justinzobel** [comment]
I have done some more work on this today.

- Calamares branding fixed
- About System branding fixed
- Firefox bookmarks fixed
- Dolphin can see my SMB shares but can't access them.
- Can install

Updated ISO http://142.93.110.189/isos/netrunner-next-amd64_2022.03.27-07.33.iso

**Comment by Justinzobel** [comment]
I've noticed Yakuake is represented twice on the system tray. It's in there once in the Plasma system tray and once as an applet. I think we can remove the applet.

**Comment by Justinzobel** [comment]
- Dolphin works previewing images in the file/folder window and in the right preview pane from `/usr/share/wallpapers/Joy/contents/images` OK.

**Comment by Justinzobel** [comment]
- [x] Wallpaper needs updating, uses the XOXO one from 21.

**Comment by star-buck** [comment]
The applet should stay, as it is a fixed position. If twice, we remove it
from systray, i need to take a look.

**Comment by star-buck** [comment]
> Updated ISO http://142.93.110.189/isos/netrunner-next-amd64_2022.03.27-07.33.iso

But why not pub.netrunner.com anymore?

**Comment by Justinzobel** [comment]
I spun up a server to build the ISOs. I can transfer them to the pub server
instead as I build them and the existing ones.

**Comment by llelectronics** [comment]
> I've noticed Yakuake is represented twice on the system tray. It's in there once in the Plasma system tray and once as an applet. I think we can remove the applet.

Thats because Yakuake now has a tray icon which is activated by default now. We had the panel icon not in tray before as we did want to have the icon always at one specific spot on the panel to appear.

**Comment by Justinzobel** [comment]
Found the config file that tells Yakuake to show the Plasma tray icon and have added it to the default-settings-applications package. Will spin ISO once I've added the fix for Win 7 Volume mixer.

**Comment by Justinzobel** [comment]
@star-buck do you want me to remove `plasma-widgets-volumewin7mixer` from the ISO entirely or just not enable it on the panel by default?

**Comment by star-buck** [comment]
@Justinzobel im revising the points at top, otherwise the conversation gets messy.
So at top, there should always be the latest points after dicussion here.
@ScarlettGatelyMoore @UriHerrera 
Please mark anything done with checkmark

**Comment by Justinzobel** [comment]
@star-buck I'm unable to tick items off, I don't think I'm part of the Github organisation/project to do so.

**Comment by star-buck** [comment]
"My computer" desktop icon, the very first thing i clicked doesnt work

**Comment by adriaandegroot** [comment]
- The *My Computer* .desktop file on the ISO uses `kcmshell5 about-extended`. That isn't available on the ISO. Issue #82 mentions a package *kcm-about-extended*, but that is "pure virtual"? I don't know enough about Debian packaging to say if that's good or bad. `kcmshell5 about-distro` shows more information than it used to, that could be a quick .desktop fix (but *kcm-about-extended* is, I think, a Netrunner specialty).
- Can confirm *Hooktube* is there and that *Science&Math* is empty.
- SMB can't test.
- Calamares issue needs more details. It looks like you're installing on a BIOS machine, which I just did (picked *erase disk* though) and at least in Dutch it was fine. Hence: needs more information.

**Comment by llelectronics** [comment]
kcm-about-extended is indeed Netrunner specific and the source can be found here: https://github.com/ds9-extras/kcm-about-extended

**Comment by Justinzobel** [comment]
Thanks Leszek, Scarlett was able to build it and we've incorporated it into the ISO build.

**Comment by ScarlettGatelyMoore** [comment]
> * The _My Computer_ .desktop file on the ISO uses `kcmshell5 about-extended`. That isn't available on the ISO. Issue [List of netrunner packages (on top of debian stable) #82](https://github.com/blue-systems/netrunner-next/issues/82) mentions a package _kcm-about-extended_, but that is "pure virtual"? I don't know enough about Debian packaging to say if that's good or bad. `kcmshell5 about-distro` shows more information than it used to, that could be a quick .desktop fix (but _kcm-about-extended_ is, I think, a Netrunner specialty).
Yes it is, fixed now.
> * Can confirm _Hooktube_ is there
Fixed now

 and that _Science&Math_ is empty.
This is the result of an ancient .kmenuedit men that still has kde 4 stuff on it, how it has worked this long is beyond me. Creating a new one once I study up on kmenuedit - WIP.
> * SMB can't test.
Still working this out. 
> * Calamares issue needs more details. It looks like you're installing on a BIOS machine, which I just did (picked _erase disk_ though) and at least in Dutch it was fine. Hence: needs more information.
Honestly I don't think this is a calamaras issue at all. They switched from live build to a tool I am unfamiliar with and installing ubuntu kernels to create iso, Our live-build scripts, configs, as far as I can see are not being pulled in. I don't reckon calamares will do the same? Admittedly my knowledge in calamares is limited. I need to see logs to see what is going on, which hopefully will show some light.

**Comment by Justinzobel** [comment]
@ScarlettGatelyMoore  Regarding menu editing I believe if you boot up the live ISO, remove the current ~/.config/menus file so the menu is default, edit the menu to how it needs and then copy the file in ~/.config/menus to the settings package it should work as we need.

**Comment by adriaandegroot** [comment]
Checked against the 04.24 ISO. These are issues to resolve:
- [ ] Empty *Science and Math* category on the live ISO, **but** that category is no longer there after installation
- [ ] *My Compuer* comes up. There's some dialog-size issues so that icons are chopped off, but the panel is scrollable to show all. There is a `@@BUILD_VERSION@@` string in there, which doesn't look right.

I can't test SMB.

**Comment by adriaandegroot** [comment]
Checking against the 04.26 ISO. The GRUB fonts issue on the live-ISO is now resolved. Empty *Science and Math* on ISO is still there. *My Computer* is still badly-sized and contains an un-substituted `@@BUILD_VERSION@@`.

**Comment by ScarlettGatelyMoore** [comment]
@star-buck I am having troubles finding anything for xapian, don't we use baloo? I think we have a package where it can be toggled off. Will get that going.

I think I found fix for samba ( outdated desktop file in a settings package ) hoping the same thing goes for dolphin. The desktop icon Add New Network works as expected. Dolphin WIP.

Is there a reason we have the math and science icons hidden? Seems like we should have things like kalgebra, kcalc, LO Math <insert kool science app here ( like kstars? marble? ) > showing in the category? Otherwise I will just delete the category.

**Comment by star-buck** [comment]
math and scienece categories shouldnt be hidden, but it should be found out why they are shown even though nothing is in there last time i checked. normally categories which contian no visible icons are auto-hidden. if there are icons in there, please list them, we might just hide or rmeove the icons there if not needed, so the categories are not hard hidden, but simply not shown when being empty

**Comment by ScarlettGatelyMoore** [comment]
Fixed the borked configs, my notes on this is in telegram chat. Apt install ( bash-completion ) doesn't work on the packages still ( but bash completion works? ) so unchecked. Menu regenerated with a few math items. We don't have science things like kstars or kalzium? @star-buck do you mind if I install one or both? Fixed entries for kcm-about-extended by going into source to get correct rc file options. The size is an issue with the intitial code hard coding the size and would need to be rewritten with current standards as Ade had mentioned. While I am all for learning new things and giving that a shot, I would rather wait for after release as my time is more valuable doing the release and it isn't completely horrible. Running new ISO now and will go through all the lists after all my fixes today.

**Comment by ScarlettGatelyMoore** [comment]
Okay... I found the apt completion apt problem... The docker package installs an apt config called docker-clean that clears the cache and disables it! thus rendering the bash-completion for the package names broken... so our options are to rm /etc/apt/apt.conf.d/docker-clean file ( possibly breaking docker? ) or leave it be and informing ( somehow ?) users how to fix the problem and let them decide? It seems to me this should not be allowed.. ( by docker team ). Anyway removing that file does fix the issue. @star-buck

**Comment by ScarlettGatelyMoore** [comment]
Menus are finally fixed. Uri found and pointed out the files overwriting all the menus I was creating. Thank you. On another note we have several custom kcms which are qwidgets and systemsettings panel is now 100% qml driven and thus they are not supported at all. They can still be brought up with kcmshell5 kcm_plasma-services etc and they still do their initial intent to bring in custom settings aka baloo is disabled at start.

**Comment by Pointedstick** [comment]
`systemsettings` should still support QtWidgets KCMs. Is Netrunner using `plasma-settings` or something? That's the one that only supports QML KCMs IIRC.

**Comment by ScarlettGatelyMoore** [comment]
@Pointedstick yes, they load fine with say systemsettings5 our_customkcm but do not show up in the control panel.

**Comment by Pointedstick** [comment]
What app is used for "the control panel"?

**Comment by ScarlettGatelyMoore** [comment]
systemsettings

**Comment by ScarlettGatelyMoore** [comment]
err systemsettings5

**Comment by Pointedstick** [comment]
`systemsettings` and `systemsettings5` are aliased to the same thing, and it still support QtWidgets KCMs.

**Comment by llelectronics** [comment]
> @Pointedstick yes, they load fine with say systemsettings5 our_customkcm but do not show up in the control panel.

We used to change the .desktop file for systemsettings for them to show up in specific catgeories. Please see: https://github.com/netrunner-common/default-systemsettings-settings/tree/Netrunner/22/kservices5
The parent category needs to exists otherwise they might show up under other. Also maybe something changed regarding the configuration options in that file for systemsettings.

**Comment by ScarlettGatelyMoore** [comment]
@Pointedstick ok, what Leszek said ^ , I have been banging my head on this for too long.

**Comment by ScarlettGatelyMoore** [comment]
I figured it out. etc/skel/.local/share/kservices5 is now the proper place. Fixing now and spinning ISO































[-ppppp

**Comment by ScarlettGatelyMoore** [comment]
@star-buck the reason IP isn't working is the CIFS support was never ported to QT5 and QT4 was removed completely from bullseye. I can file a bug or beg someone.. who? to port it as it would be a bit of a learning curve and time for me to figure it out.
Also the Add Network Drive already has the exec bit on it. Not sure how to make that window go away. researching. Lost and Found I fixed last night.

**Comment by ScarlettGatelyMoore** [comment]
fixed executable without confirmation. Only thing holding up release is samba-mounter lack of CIFS support.

**Comment by ScarlettGatelyMoore** [comment]
https://invent.kde.org/system/samba-mounter/-/issues/1

**Comment by ScarlettGatelyMoore** [comment]
I don't have a dedicated windows box to fully debug this. My samba share does show up and mount. Mounting samba:  "smb://192.168.42.6/Scarlett Home/-/home/scarlett/Network/Scarlett Home" by IP and by hostname. Is your t2 an older windows/machine? I am reading there can be issues with those and 1.0 needs to be enabled. Will look into enabling this by default if it isn't. I think we misunderstood on win 7 volume and removed it. Fixing now. Adding marble-maps to our install list, should fix that issue.

**Comment by ScarlettGatelyMoore** [comment]
@star-buck can you please post the output of cat ~/.xsession-errors | grep samba

**Comment by ScarlettGatelyMoore** [comment]
add network: i can find smb network shares, but it STILL doesnt accept any IP

I need more info ^^ see above. As it works for me, both by IP address and by hostname. My problem was I had not actually shared any files on the host. oops. So I need logs as I am making wild guesses as to what is going on with @star-buck shares :(
Al the other points fixed and building new ISO now.

**Comment by ScarlettGatelyMoore** [comment]
Not letting me check boxes :( All done except I cannot reproduce samba issue. @Justinzobel @UriHerrera Will you please try to reproduce? I need logs to work with. I have no idea what is failing as it works for me.
More fixes on next ISO with systemsettings and no longer relevant/broken kcms.

**Comment by Justinzobel** [comment]
ISO netrunner-next-amd64_2022.07.27-17.20.iso

- [x] WiFi Working for me
- [x] Add Network: Working via IP and DNS name and FQDN (including .local)
- [x] add network drive: the icon under Network folder is not executable default, should be added permission without re-asking again
- [x] there is an empty category Lost and Found in menu
- [x] Volume 7 win is missing before systray, and in systray, the regular volume icon should be hidden (as it was previous netrunner 21)
- [x] marble: get directions is still not working for years now, please check upstream
- [x] wrong plymouth start theme
- [x] yakuake comes up open when logging in
- [x] dolphin completely missing all configs
- [x] also many other settings like window plcaements, etc all gone
- [x] panel at bottom missing yakuake, possibly other things (not sure as all over configs are wrong)
---------
- [x] System Settings: should be normal sidebar view, not old grid
- [x] System Settings: Color scheme: error about missing color scheme, needs to be checked to get rid of that message
- [x] check why for "apt install" no longer the TAB fucntion works to suggest autocomplete any package name 
- [x] install iputils-ping
- [x] stop xapian api process from going off and clogging the whole machine (we fixed this long time ago, not it seems it is back)
- [x] FF: Remove "Import Bookmarks" item from Bookmark category
- [x] STILL cannot access any SMB network drives,  they work fine from the same machine with e.g. Manjaro KDE
- [x] that local likely prevents me also from accessing zynthbox via browser by simply typing: zynthbox.local , so it needs fixing priority, as I cant do any work from this machine right now
- [x] There is an EMPTY category shown (Science&Math) even though no icons are there... this should not be, so it is some issue or reason
- [x] "My computer" desktop icon doesnt work
- [x] Hooktube is still there?
- [x] CALAMARES FAILS to install
- [x] grub: after installation, menu should read "Netrunner 22" if to pick from various installed os
- [x] Dolphin: Has NO PREVIEWS options
- [x] Dolphin: doesnt know the SMB protocol, shows no networks
- [x] Dolphin: Network: Add Network folder: KCM not found, error
- [x] boot up from usb: lets remove any auto-disk check routine completely from that iso
- [x] Calamares, GRUB, ABOUT CONFIG: replace all VERSIONS with "Netrunner 22", NOT 21 or XOXO
- [x] Calamares icon is MISSING on desktop in LIVE MODE (dont show it AFTER installed!)
- [x] Firefox: Link to Netrunner forum is WRONG, should be: https://support.blue-systems.com/
- [x] Menu: remove/hide "TERMIT"
- [x] Menu: Web: remove "hooktube" webapps
- [x] systray: hide Yakuake
- [x] Disable Volume Mixer Win7
- [x] use this wallpaper default to replace XOXO: https://my.opendesktop.org/s/jsFNQpc5QLBzcCw

Checking #87 now.
