### ISSUE TITLE
NR GENERAL Checklist

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#87]
https://pub.netrunner.com/.testing/?C=M;O=D

== BASIC TESTS ==

* do these basic tests with every new iso:
-
* basic tests:
* [ ] ALL MENU ITEMS THERE #127 
* [x] menu sorted alphabetic, that is the categories and the menu entries
* [x] WIFI works?
* [x] installation works
* [x] german install works
* [x] uefi install works
* [x] logout/login works after second boot
* [x] tty1 - tty7 ALT+STRG+F1 - F7
* [x] Version name and number is correct? in calamares, in My Computer,after install in grub?
* [x] sddm artwork is correct
* [x] Sound works
* [x] sftp + smb connections work
* [x] Samba-Mounter works (even after reboot)
* [x] sudo apt update executes and does not throw errors?
* [ ] Discover updating packages shows up in systray and works after apt update?
* [x] Synaptic installing qmmp app works
* [x] synaptic: refresh works after uncommenting "testing"

----

* plasma checks:
* [x] meta/"Windows" key works to invoke and close menu
* [x] drag windows from titlebar
* [x] Panel configured correctly
* [x] Artwork configured correctly
* [x] Desktop: Right Click menu configured correctly, add new text-file
* [x] right-click: adding a miniprogram (e.g. clock) to desktop works?

----

* software checks:
* [x] firefox loads
* [x] thunderbird loads
* [x] steam loads
* [x] net-tools installed
* [x] inxi installed
* [x] every app starts

----

* firefox checks:
* [x] ublock works?
* [x] ublock filter rules correct with blocking google hidden stuff?
* [x] downloading google logo works?
* [x] magnet torrent works? https://www.limetorrents.cc/Introducing-UNIX-and-Linux-(Grassroots)-by-Mike-Joy--True-PDF--torrent-8660949.html

**Comment by Justinzobel** [comment]
Tested on live ISO 2022.04.12-09.04 in VirtualBox

== BASIC TESTS ==
* basic tests:
* [x] installation works
* [ ] german install works
* [x] uefi install works
* [x] logout/login works after second boot
* [x] tty1 - tty7 ALT+STRG+F1 - F7
**I'm unfamiliar with STRG but Ctrl Alt 1-7 loads TTY 1-7 and I tested ability to login on TTY 3 OK**
* [x] Version name and number is correct? in calamares, in My Computer,after install in grub?
* [x] sddm artwork is correct
* [x] Sound works
* [x] Network works
* [x] sftp + smb connections work:
 - 
* [x] Samba-Mounter works (even after reboot)
* [x] apt-get update does not throw errors
* [x] Synaptic installing qmmp app works
* [x] synaptic: refresh works after uncommenting "testing"

----

* plasma checks:
* [x] meta key works to invoke menu
* [x] menu sorted alphabetic, that is the categories and the menu entries
* [x] drag windows from titlebar
* [x] Panel configured correctly
* [x] Artwork configured correctly
* [ ] Right Click menu configured correctly
**Need clarification on this**

----

* software checks:
* [x] firefox loads
* [x] thunderbird loads
* [x] steam loads
**Menu shortcut places icon on desktop and that can be used to open steam**
* [x] net-tools installed
* [x] inxi installed
* [x] every app starts


----

* firefox checks:
* [x] ublock works?
* [ ] ublock filter rules correct with blocking google hidden stuff?
**Need clarification on this**
* [ ] downloading google logo works?
**Need clarification on this, does this mean right click and save as on the Google Logo on www.google.com?**
* [x] magnet torrent works? https://www.limetorrents.cc/Introducing-UNIX-and-Linux-(Grassroots)-by-Mike-Joy--True-PDF--torrent-8660949.html - Tested https://linuxtracker.org/?page=torrent-details&id=3076bfb5f1997c0c541e1590ec2cbd7f4c15601d instead

**Comment by Justinzobel** [comment]
Note: I've copied and pasted it into a comment so as not to mark off the top comment. I think it is better this way as each person can mark off the same checklist.

**Comment by Justinzobel** [comment]
ISO netrunner-next-amd64_2022.07.27-17.20.iso

== BASIC TESTS ==
* basic tests:
* [x] WIFI works?
* [x] installation works
* **not tested** [ ] german install works
* [x] uefi install works
* [x] logout/login works after second boot
* [x] tty1 - tty7 ALT+STRG+F1 - F7
* [x] Version name and number is correct? in calamares, in My Computer,after install in grub?
* [x] sddm artwork is correct
* [ ] Sound works
**I see no audio device on my Dell laptop (older model)**
* [x] sftp + smb connections work
* [x] Samba-Mounter works (even after reboot)
* [x] apt-get update does not throw errors
* [x] Synaptic installing qmmp app works

----

* plasma checks:
* [x] meta key works to invoke menu
* [x] menu sorted alphabetic, that is the categories and the menu entries
* [x] drag windows from titlebar
* [x] Panel configured correctly
* [x] Artwork configured correctly
* [x] Right Click menu configured correctly

----

* software checks:
* [x] firefox loads
* [x] thunderbird loads
* [x] steam loads
* [x] net-tools installed
* [x] inxi installed
* **not tested** [ ] every app starts

----

* firefox checks:
* [x] ublock works?
* [x] downloading google logo works?
* [x] magnet torrent works? https://www.limetorrents.cc/Introducing-UNIX-and-Linux-(Grassroots)-by-Mike-Joy--True-PDF--torrent-8660949.html

**Need clarification on these items:**
* [ ] ublock filter rules correct with blocking google hidden stuff?
* [ ] synaptic: refresh works after uncommenting "testing" - **No testing repo added**

**Comment by Justinzobel** [comment]
Sound confirmed working on my desktop via a USB to 3.5mm sound device.
