### ISSUE TITLE
Netrunner 22, still TODO cont.

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-next#88]
https://pub.netrunner.com/.testing/

- [x] after installation to disk, the "LIVE" user is NOT removed and default shown in login
- [x] about kcm: missing build info
- [x] system after installation is completely overloaded (load averages of 3.x), heater fans are spinning even when doing nothing after log in...
![Screenshot_20220816_121406](https://user-images.githubusercontent.com/840070/184855412-297575d4-6f5b-4a83-b4aa-936982e2ce3c.png)
- [x] set these systray entries to this:
![Screenshot_20220816_121109](https://user-images.githubusercontent.com/840070/184855596-0208aa8e-5684-464e-beff-cf46d625cb01.png)
- [x] remove smplayer
- [x] add vlc
- [x] add "iputils-ping" package

**Comment by UriHerrera** [comment]
I've checked the boxes, and I applied all the requested changes. This ISO is the latest available: https://pub.netrunner.com/.testing/netrunner-next-amd64_2022.08.19-03.13.iso.
